name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  matrix-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3", "3.4"]

    name: Ruby ${{ matrix.ruby }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: RSpec
        run: bundle exec rake

  test:
    needs: matrix-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check status
        run: |
          RESULT="${{ needs.matrix-test.result }}"
          if [ "$RESULT" == "success" ] || [ "$RESULT" == "skipped" ]; then
            echo "All required tests passed!"
            exit 0
          else
            echo "Required tests failed."
            exit 1
          fi
